<?php

declare(strict_types=1);

namespace ExeQue\FluentAssert\Concerns;

use BadMethodCallException;

/**
 * This file is auto-generated. Do not edit it manually.
 *
 * @method \static all(callable ...$callbacks)
 * @method \static allAlnum($message = '')
 * @method \static allAlpha($message = '')
 * @method \static allArrayContains($value, $message = '')
 * @method \static allBoolean($message = '')
 * @method \static allClassExists($message = '')
 * @method \static allContains($subString, $message = '')
 * @method \static allCount($number, $message = '')
 * @method \static allCountBetween($min, $max, $message = '')
 * @method \static allDigits($message = '')
 * @method \static allDirectory($message = '')
 * @method \static allEmail($message = '')
 * @method \static allEndsWith($suffix, $message = '')
 * @method \static allEnumCaseExists($enumClass, $message = '')
 * @method \static allEnumValueExists($enumClass, $message = '')
 * @method \static allEq($expect, $message = '')
 * @method \static allFalse($message = '')
 * @method \static allFile($message = '')
 * @method \static allFileExists($message = '')
 * @method \static allFloat($message = '')
 * @method \static allFulfills($callback, $message = '')
 * @method \static allGreaterThan($limit, $message = '')
 * @method \static allGreaterThanEq($limit, $message = '')
 * @method \static allHasIndices($message = '')
 * @method \static allImplementsInterface($interface, $message = '')
 * @method \static allInArray($values, $message = '')
 * @method \static allInstancedPropertyExists($name, $message = '')
 * @method \static allInteger($message = '')
 * @method \static allIntegerish($message = '')
 * @method \static allInterfaceExists($message = '')
 * @method \static allIp($message = '')
 * @method \static allIpv4($message = '')
 * @method \static allIpv6($message = '')
 * @method \static allIsAOf($class, $message = '')
 * @method \static allIsAnyOf($classes, $message = '')
 * @method \static allIsArray($message = '')
 * @method \static allIsArrayAccessible($message = '')
 * @method \static allIsCallable($message = '')
 * @method \static allIsCountable($message = '')
 * @method \static allIsEmpty($message = '')
 * @method \static allIsInstanceOf($class, $message = '')
 * @method \static allIsInstanceOfAny($classes, $message = '')
 * @method \static allIsIterable($message = '')
 * @method \static allIsList($message = '')
 * @method \static allIsMap($message = '')
 * @method \static allIsNonEmptyList($message = '')
 * @method \static allIsNonEmptyMap($message = '')
 * @method \static allIsNotA($class, $message = '')
 * @method \static allKeyExists($key, $message = '')
 * @method \static allKeyNotExists($key, $message = '')
 * @method \static allKeysExists($keys, $message = '')
 * @method \static allLength($length, $message = '')
 * @method \static allLengthBetween($min, $max, $message = '')
 * @method \static allLessThan($limit, $message = '')
 * @method \static allLessThanEq($limit, $message = '')
 * @method \static allLower($message = '')
 * @method \static allMaxCount($max, $message = '')
 * @method \static allMaxLength($max, $message = '')
 * @method \static allMethodExists($method, $message = '')
 * @method \static allMethodNotExists($method, $message = '')
 * @method \static allMinCount($min, $message = '')
 * @method \static allMinLength($min, $message = '')
 * @method \static allNatural($message = '')
 * @method \static allNotContains($subString, $message = '')
 * @method \static allNotEmpty($message = '')
 * @method \static allNotEndsWith($suffix, $message = '')
 * @method \static allNotEq($expect, $message = '')
 * @method \static allNotFalse($message = '')
 * @method \static allNotInstanceOf($class, $message = '')
 * @method \static allNotNull($message = '')
 * @method \static allNotRegex($pattern, $message = '')
 * @method \static allNotSame($expect, $message = '')
 * @method \static allNotStartsWith($prefix, $message = '')
 * @method \static allNotWhitespaceOnly($message = '')
 * @method \static allNull($message = '')
 * @method \static allNullOrAlnum($message = '')
 * @method \static allNullOrAlpha($message = '')
 * @method \static allNullOrArrayContains($value, $message = '')
 * @method \static allNullOrBoolean($message = '')
 * @method \static allNullOrClassExists($message = '')
 * @method \static allNullOrContains($subString, $message = '')
 * @method \static allNullOrCount($number, $message = '')
 * @method \static allNullOrCountBetween($min, $max, $message = '')
 * @method \static allNullOrDigits($message = '')
 * @method \static allNullOrDirectory($message = '')
 * @method \static allNullOrEmail($message = '')
 * @method \static allNullOrEndsWith($suffix, $message = '')
 * @method \static allNullOrEnumCaseExists($enumClass, $message = '')
 * @method \static allNullOrEnumValueExists($enumClass, $message = '')
 * @method \static allNullOrEq($expect, $message = '')
 * @method \static allNullOrFalse($message = '')
 * @method \static allNullOrFile($message = '')
 * @method \static allNullOrFileExists($message = '')
 * @method \static allNullOrFloat($message = '')
 * @method \static allNullOrFulfills($callback, $message = '')
 * @method \static allNullOrGreaterThan($limit, $message = '')
 * @method \static allNullOrGreaterThanEq($limit, $message = '')
 * @method \static allNullOrHasIndices($message = '')
 * @method \static allNullOrImplementsInterface($interface, $message = '')
 * @method \static allNullOrInArray($values, $message = '')
 * @method \static allNullOrInstancedPropertyExists($name, $message = '')
 * @method \static allNullOrInteger($message = '')
 * @method \static allNullOrIntegerish($message = '')
 * @method \static allNullOrInterfaceExists($message = '')
 * @method \static allNullOrIp($message = '')
 * @method \static allNullOrIpv4($message = '')
 * @method \static allNullOrIpv6($message = '')
 * @method \static allNullOrIsAOf($class, $message = '')
 * @method \static allNullOrIsAnyOf($classes, $message = '')
 * @method \static allNullOrIsArray($message = '')
 * @method \static allNullOrIsArrayAccessible($message = '')
 * @method \static allNullOrIsCallable($message = '')
 * @method \static allNullOrIsCountable($message = '')
 * @method \static allNullOrIsEmpty($message = '')
 * @method \static allNullOrIsInstanceOf($class, $message = '')
 * @method \static allNullOrIsInstanceOfAny($classes, $message = '')
 * @method \static allNullOrIsIterable($message = '')
 * @method \static allNullOrIsList($message = '')
 * @method \static allNullOrIsMap($message = '')
 * @method \static allNullOrIsNonEmptyList($message = '')
 * @method \static allNullOrIsNonEmptyMap($message = '')
 * @method \static allNullOrIsNotA($class, $message = '')
 * @method \static allNullOrKeyExists($key, $message = '')
 * @method \static allNullOrKeyNotExists($key, $message = '')
 * @method \static allNullOrKeysExists($keys, $message = '')
 * @method \static allNullOrLength($length, $message = '')
 * @method \static allNullOrLengthBetween($min, $max, $message = '')
 * @method \static allNullOrLessThan($limit, $message = '')
 * @method \static allNullOrLessThanEq($limit, $message = '')
 * @method \static allNullOrLower($message = '')
 * @method \static allNullOrMaxCount($max, $message = '')
 * @method \static allNullOrMaxLength($max, $message = '')
 * @method \static allNullOrMethodExists($method, $message = '')
 * @method \static allNullOrMethodNotExists($method, $message = '')
 * @method \static allNullOrMinCount($min, $message = '')
 * @method \static allNullOrMinLength($min, $message = '')
 * @method \static allNullOrNatural($message = '')
 * @method \static allNullOrNotContains($subString, $message = '')
 * @method \static allNullOrNotEmpty($message = '')
 * @method \static allNullOrNotEndsWith($suffix, $message = '')
 * @method \static allNullOrNotEq($expect, $message = '')
 * @method \static allNullOrNotFalse($message = '')
 * @method \static allNullOrNotInstanceOf($class, $message = '')
 * @method \static allNullOrNotNull($message = '')
 * @method \static allNullOrNotRegex($pattern, $message = '')
 * @method \static allNullOrNotSame($expect, $message = '')
 * @method \static allNullOrNotStartsWith($prefix, $message = '')
 * @method \static allNullOrNotWhitespaceOnly($message = '')
 * @method \static allNullOrNumeric($message = '')
 * @method \static allNullOrObject($message = '')
 * @method \static allNullOrOneOf($values, $message = '')
 * @method \static allNullOrPositiveInteger($message = '')
 * @method \static allNullOrPrivatePropertyExists($name, $message = '')
 * @method \static allNullOrPropertyExists($property, $message = '')
 * @method \static allNullOrPropertyNotExists($property, $message = '')
 * @method \static allNullOrProtectedPropertyExists($name, $message = '')
 * @method \static allNullOrPublicPropertyExists($name, $message = '')
 * @method \static allNullOrRange($min, $max, $message = '')
 * @method \static allNullOrReadable($message = '')
 * @method \static allNullOrRegex($pattern, $message = '')
 * @method \static allNullOrResource($type = null, $message = '')
 * @method \static allNullOrSame($expect, $message = '')
 * @method \static allNullOrScalar($message = '')
 * @method \static allNullOrStartsWith($prefix, $message = '')
 * @method \static allNullOrStartsWithLetter($message = '')
 * @method \static allNullOrStaticPropertyExists($name, $message = '')
 * @method \static allNullOrString($message = '')
 * @method \static allNullOrStringNotEmpty($message = '')
 * @method \static allNullOrSubclassOf($class, $message = '')
 * @method \static allNullOrThrows($class = 'Exception', $message = '')
 * @method \static allNullOrTrue($message = '')
 * @method \static allNullOrType($type, $message = '')
 * @method \static allNullOrUnicodeLetters($message = '')
 * @method \static allNullOrUniqueValues($message = '')
 * @method \static allNullOrUpper($message = '')
 * @method \static allNullOrUuid($message = '')
 * @method \static allNullOrValidArrayKey($message = '')
 * @method \static allNullOrWritable($message = '')
 * @method \static allNumeric($message = '')
 * @method \static allObject($message = '')
 * @method \static allOneOf($values, $message = '')
 * @method \static allPositiveInteger($message = '')
 * @method \static allPrivatePropertyExists($name, $message = '')
 * @method \static allPropertyExists($property, $message = '')
 * @method \static allPropertyNotExists($property, $message = '')
 * @method \static allProtectedPropertyExists($name, $message = '')
 * @method \static allPublicPropertyExists($name, $message = '')
 * @method \static allRange($min, $max, $message = '')
 * @method \static allReadable($message = '')
 * @method \static allRegex($pattern, $message = '')
 * @method \static allResource($type = null, $message = '')
 * @method \static allSame($expect, $message = '')
 * @method \static allScalar($message = '')
 * @method \static allStartsWith($prefix, $message = '')
 * @method \static allStartsWithLetter($message = '')
 * @method \static allStaticPropertyExists($name, $message = '')
 * @method \static allString($message = '')
 * @method \static allStringNotEmpty($message = '')
 * @method \static allSubclassOf($class, $message = '')
 * @method \static allThrows($class = 'Exception', $message = '')
 * @method \static allTrue($message = '')
 * @method \static allType($type, $message = '')
 * @method \static allUnicodeLetters($message = '')
 * @method \static allUniqueValues($message = '')
 * @method \static allUpper($message = '')
 * @method \static allUuid($message = '')
 * @method \static allValidArrayKey($message = '')
 * @method \static allWritable($message = '')
 * @method \static alnum($message = '')
 * @method \static alpha($message = '')
 * @method \static and(callable ...$callbacks)
 * @method \static any(callable ...$callbacks)
 * @method \static arrayContains($value, $message = '')
 * @method \static at(callable|string|int $index, callable $callback, string $message = '')
 * @method \static atMany(array $map, string $message = '')
 * @method \static boolean($message = '')
 * @method \static classExists($message = '')
 * @method \static contains($subString, $message = '')
 * @method \static count($number, $message = '')
 * @method \static countBetween($min, $max, $message = '')
 * @method \static digits($message = '')
 * @method \static directory($message = '')
 * @method \static duplicate()
 * @method \static email($message = '')
 * @method \static endsWith($suffix, $message = '')
 * @method \static enumCaseExists($enumClass, $message = '')
 * @method \static enumValueExists($enumClass, $message = '')
 * @method \static eq($expect, $message = '')
 * @method \static false($message = '')
 * @method \static file($message = '')
 * @method \static fileExists($message = '')
 * @method \static float($message = '')
 * @method \static forEach(callable $callback)
 * @method \static forKeys(callable $callback)
 * @method \static fulfills($callback, $message = '')
 * @method \static greaterThan($limit, $message = '')
 * @method \static greaterThanEq($limit, $message = '')
 * @method \static hasIndices($message = '')
 * @method \static implementsInterface($interface, $message = '')
 * @method \static inArray($values, $message = '')
 * @method \static instancedPropertyExists($name, $message = '')
 * @method \static integer($message = '')
 * @method \static integerish($message = '')
 * @method \static interfaceExists($message = '')
 * @method \static ip($message = '')
 * @method \static ipv4($message = '')
 * @method \static ipv6($message = '')
 * @method \static isAOf($class, $message = '')
 * @method \static isAnyOf($classes, $message = '')
 * @method \static isArray($message = '')
 * @method \static isArrayAccessible($message = '')
 * @method \static isCallable($message = '')
 * @method \static isCountable($message = '')
 * @method \static isEmpty($message = '')
 * @method \static isInstanceOf($class, $message = '')
 * @method \static isInstanceOfAny($classes, $message = '')
 * @method \static isIterable($message = '')
 * @method \static isList($message = '')
 * @method \static isMap($message = '')
 * @method \static isNonEmptyList($message = '')
 * @method \static isNonEmptyMap($message = '')
 * @method \static isNotA($class, $message = '')
 * @method \static keyExists($key, $message = '')
 * @method \static keyNotExists($key, $message = '')
 * @method \static keysExists($keys, $message = '')
 * @method \static length($length, $message = '')
 * @method \static lengthBetween($min, $max, $message = '')
 * @method \static lessThan($limit, $message = '')
 * @method \static lessThanEq($limit, $message = '')
 * @method \static lower($message = '')
 * @method \static maxCount($max, $message = '')
 * @method \static maxLength($max, $message = '')
 * @method \static methodExists($method, $message = '')
 * @method \static methodNotExists($method, $message = '')
 * @method \static minCount($min, $message = '')
 * @method \static minLength($min, $message = '')
 * @method \static natural($message = '')
 * @method \static notContains($subString, $message = '')
 * @method \static notEmpty($message = '')
 * @method \static notEndsWith($suffix, $message = '')
 * @method \static notEq($expect, $message = '')
 * @method \static notFalse($message = '')
 * @method \static notInstanceOf($class, $message = '')
 * @method \static notNull($message = '')
 * @method \static notRegex($pattern, $message = '')
 * @method \static notSame($expect, $message = '')
 * @method \static notStartsWith($prefix, $message = '')
 * @method \static notWhitespaceOnly($message = '')
 * @method \static null($message = '')
 * @method \static nullOr(callable $callback)
 * @method \static nullOrAlnum($message = '')
 * @method \static nullOrAlpha($message = '')
 * @method \static nullOrArrayContains($value, $message = '')
 * @method \static nullOrBoolean($message = '')
 * @method \static nullOrClassExists($message = '')
 * @method \static nullOrContains($subString, $message = '')
 * @method \static nullOrCount($number, $message = '')
 * @method \static nullOrCountBetween($min, $max, $message = '')
 * @method \static nullOrDigits($message = '')
 * @method \static nullOrDirectory($message = '')
 * @method \static nullOrEmail($message = '')
 * @method \static nullOrEndsWith($suffix, $message = '')
 * @method \static nullOrEnumCaseExists($enumClass, $message = '')
 * @method \static nullOrEnumValueExists($enumClass, $message = '')
 * @method \static nullOrEq($expect, $message = '')
 * @method \static nullOrFalse($message = '')
 * @method \static nullOrFile($message = '')
 * @method \static nullOrFileExists($message = '')
 * @method \static nullOrFloat($message = '')
 * @method \static nullOrFulfills($callback, $message = '')
 * @method \static nullOrGreaterThan($limit, $message = '')
 * @method \static nullOrGreaterThanEq($limit, $message = '')
 * @method \static nullOrHasIndices($message = '')
 * @method \static nullOrImplementsInterface($interface, $message = '')
 * @method \static nullOrInArray($values, $message = '')
 * @method \static nullOrInstancedPropertyExists($name, $message = '')
 * @method \static nullOrInteger($message = '')
 * @method \static nullOrIntegerish($message = '')
 * @method \static nullOrInterfaceExists($message = '')
 * @method \static nullOrIp($message = '')
 * @method \static nullOrIpv4($message = '')
 * @method \static nullOrIpv6($message = '')
 * @method \static nullOrIsAOf($class, $message = '')
 * @method \static nullOrIsAnyOf($classes, $message = '')
 * @method \static nullOrIsArray($message = '')
 * @method \static nullOrIsArrayAccessible($message = '')
 * @method \static nullOrIsCallable($message = '')
 * @method \static nullOrIsCountable($message = '')
 * @method \static nullOrIsEmpty($message = '')
 * @method \static nullOrIsInstanceOf($class, $message = '')
 * @method \static nullOrIsInstanceOfAny($classes, $message = '')
 * @method \static nullOrIsIterable($message = '')
 * @method \static nullOrIsList($message = '')
 * @method \static nullOrIsMap($message = '')
 * @method \static nullOrIsNonEmptyList($message = '')
 * @method \static nullOrIsNonEmptyMap($message = '')
 * @method \static nullOrIsNotA($class, $message = '')
 * @method \static nullOrKeyExists($key, $message = '')
 * @method \static nullOrKeyNotExists($key, $message = '')
 * @method \static nullOrKeysExists($keys, $message = '')
 * @method \static nullOrLength($length, $message = '')
 * @method \static nullOrLengthBetween($min, $max, $message = '')
 * @method \static nullOrLessThan($limit, $message = '')
 * @method \static nullOrLessThanEq($limit, $message = '')
 * @method \static nullOrLower($message = '')
 * @method \static nullOrMaxCount($max, $message = '')
 * @method \static nullOrMaxLength($max, $message = '')
 * @method \static nullOrMethodExists($method, $message = '')
 * @method \static nullOrMethodNotExists($method, $message = '')
 * @method \static nullOrMinCount($min, $message = '')
 * @method \static nullOrMinLength($min, $message = '')
 * @method \static nullOrNatural($message = '')
 * @method \static nullOrNotContains($subString, $message = '')
 * @method \static nullOrNotEmpty($message = '')
 * @method \static nullOrNotEndsWith($suffix, $message = '')
 * @method \static nullOrNotEq($expect, $message = '')
 * @method \static nullOrNotFalse($message = '')
 * @method \static nullOrNotInstanceOf($class, $message = '')
 * @method \static nullOrNotNull($message = '')
 * @method \static nullOrNotRegex($pattern, $message = '')
 * @method \static nullOrNotSame($expect, $message = '')
 * @method \static nullOrNotStartsWith($prefix, $message = '')
 * @method \static nullOrNotWhitespaceOnly($message = '')
 * @method \static nullOrNumeric($message = '')
 * @method \static nullOrObject($message = '')
 * @method \static nullOrOneOf($values, $message = '')
 * @method \static nullOrPositiveInteger($message = '')
 * @method \static nullOrPrivatePropertyExists($name, $message = '')
 * @method \static nullOrPropertyExists($property, $message = '')
 * @method \static nullOrPropertyNotExists($property, $message = '')
 * @method \static nullOrProtectedPropertyExists($name, $message = '')
 * @method \static nullOrPublicPropertyExists($name, $message = '')
 * @method \static nullOrRange($min, $max, $message = '')
 * @method \static nullOrReadable($message = '')
 * @method \static nullOrRegex($pattern, $message = '')
 * @method \static nullOrResource($type = null, $message = '')
 * @method \static nullOrSame($expect, $message = '')
 * @method \static nullOrScalar($message = '')
 * @method \static nullOrStartsWith($prefix, $message = '')
 * @method \static nullOrStartsWithLetter($message = '')
 * @method \static nullOrStaticPropertyExists($name, $message = '')
 * @method \static nullOrString($message = '')
 * @method \static nullOrStringNotEmpty($message = '')
 * @method \static nullOrSubclassOf($class, $message = '')
 * @method \static nullOrThrows($class = 'Exception', $message = '')
 * @method \static nullOrTrue($message = '')
 * @method \static nullOrType($type, $message = '')
 * @method \static nullOrUnicodeLetters($message = '')
 * @method \static nullOrUniqueValues($message = '')
 * @method \static nullOrUpper($message = '')
 * @method \static nullOrUuid($message = '')
 * @method \static nullOrValidArrayKey($message = '')
 * @method \static nullOrWritable($message = '')
 * @method \static numeric($message = '')
 * @method \static object($message = '')
 * @method \static oneOf($values, $message = '')
 * @method \static or(callable ...$callbacks)
 * @method \static positiveInteger($message = '')
 * @method \static privatePropertyExists($name, $message = '')
 * @method \static propertyExists($property, $message = '')
 * @method \static propertyNotExists($property, $message = '')
 * @method \static protectedPropertyExists($name, $message = '')
 * @method \static publicPropertyExists($name, $message = '')
 * @method \static range($min, $max, $message = '')
 * @method \static readable($message = '')
 * @method \static regex($pattern, $message = '')
 * @method \static resource($type = null, $message = '')
 * @method \static same($expect, $message = '')
 * @method \static scalar($message = '')
 * @method \static startsWith($prefix, $message = '')
 * @method \static startsWithLetter($message = '')
 * @method \static staticPropertyExists($name, $message = '')
 * @method \static string($message = '')
 * @method \static stringNotEmpty($message = '')
 * @method \static subclassOf($class, $message = '')
 * @method \static throws($class = 'Exception', $message = '')
 * @method \static true($message = '')
 * @method \static type($type, $message = '')
 * @method \static unicodeLetters($message = '')
 * @method \static uniqueValues($message = '')
 * @method \static upper($message = '')
 * @method \static uuid($message = '')
 * @method \static validArrayKey($message = '')
 * @method \static when(mixed $condition, callable $then, callable|null $otherwise = null)
 * @method \static whenAt(string|int $key, callable $then, callable|null $otherwise = null)
 * @method \static writable($message = '')
 *
 * @internal
 */
trait DocblockMixin
{
    protected array $coveredMethods = ["all","allAlnum","allAlpha","allArrayContains","allBoolean","allClassExists","allContains","allCount","allCountBetween","allDigits","allDirectory","allEmail","allEndsWith","allEnumCaseExists","allEnumValueExists","allEq","allFalse","allFile","allFileExists","allFloat","allFulfills","allGreaterThan","allGreaterThanEq","allHasIndices","allImplementsInterface","allInArray","allInstancedPropertyExists","allInteger","allIntegerish","allInterfaceExists","allIp","allIpv4","allIpv6","allIsAOf","allIsAnyOf","allIsArray","allIsArrayAccessible","allIsCallable","allIsCountable","allIsEmpty","allIsInstanceOf","allIsInstanceOfAny","allIsIterable","allIsList","allIsMap","allIsNonEmptyList","allIsNonEmptyMap","allIsNotA","allKeyExists","allKeyNotExists","allKeysExists","allLength","allLengthBetween","allLessThan","allLessThanEq","allLower","allMaxCount","allMaxLength","allMethodExists","allMethodNotExists","allMinCount","allMinLength","allNatural","allNotContains","allNotEmpty","allNotEndsWith","allNotEq","allNotFalse","allNotInstanceOf","allNotNull","allNotRegex","allNotSame","allNotStartsWith","allNotWhitespaceOnly","allNull","allNullOrAlnum","allNullOrAlpha","allNullOrArrayContains","allNullOrBoolean","allNullOrClassExists","allNullOrContains","allNullOrCount","allNullOrCountBetween","allNullOrDigits","allNullOrDirectory","allNullOrEmail","allNullOrEndsWith","allNullOrEnumCaseExists","allNullOrEnumValueExists","allNullOrEq","allNullOrFalse","allNullOrFile","allNullOrFileExists","allNullOrFloat","allNullOrFulfills","allNullOrGreaterThan","allNullOrGreaterThanEq","allNullOrHasIndices","allNullOrImplementsInterface","allNullOrInArray","allNullOrInstancedPropertyExists","allNullOrInteger","allNullOrIntegerish","allNullOrInterfaceExists","allNullOrIp","allNullOrIpv4","allNullOrIpv6","allNullOrIsAOf","allNullOrIsAnyOf","allNullOrIsArray","allNullOrIsArrayAccessible","allNullOrIsCallable","allNullOrIsCountable","allNullOrIsEmpty","allNullOrIsInstanceOf","allNullOrIsInstanceOfAny","allNullOrIsIterable","allNullOrIsList","allNullOrIsMap","allNullOrIsNonEmptyList","allNullOrIsNonEmptyMap","allNullOrIsNotA","allNullOrKeyExists","allNullOrKeyNotExists","allNullOrKeysExists","allNullOrLength","allNullOrLengthBetween","allNullOrLessThan","allNullOrLessThanEq","allNullOrLower","allNullOrMaxCount","allNullOrMaxLength","allNullOrMethodExists","allNullOrMethodNotExists","allNullOrMinCount","allNullOrMinLength","allNullOrNatural","allNullOrNotContains","allNullOrNotEmpty","allNullOrNotEndsWith","allNullOrNotEq","allNullOrNotFalse","allNullOrNotInstanceOf","allNullOrNotNull","allNullOrNotRegex","allNullOrNotSame","allNullOrNotStartsWith","allNullOrNotWhitespaceOnly","allNullOrNumeric","allNullOrObject","allNullOrOneOf","allNullOrPositiveInteger","allNullOrPrivatePropertyExists","allNullOrPropertyExists","allNullOrPropertyNotExists","allNullOrProtectedPropertyExists","allNullOrPublicPropertyExists","allNullOrRange","allNullOrReadable","allNullOrRegex","allNullOrResource","allNullOrSame","allNullOrScalar","allNullOrStartsWith","allNullOrStartsWithLetter","allNullOrStaticPropertyExists","allNullOrString","allNullOrStringNotEmpty","allNullOrSubclassOf","allNullOrThrows","allNullOrTrue","allNullOrType","allNullOrUnicodeLetters","allNullOrUniqueValues","allNullOrUpper","allNullOrUuid","allNullOrValidArrayKey","allNullOrWritable","allNumeric","allObject","allOneOf","allPositiveInteger","allPrivatePropertyExists","allPropertyExists","allPropertyNotExists","allProtectedPropertyExists","allPublicPropertyExists","allRange","allReadable","allRegex","allResource","allSame","allScalar","allStartsWith","allStartsWithLetter","allStaticPropertyExists","allString","allStringNotEmpty","allSubclassOf","allThrows","allTrue","allType","allUnicodeLetters","allUniqueValues","allUpper","allUuid","allValidArrayKey","allWritable","alnum","alpha","and","any","arrayContains","at","atMany","boolean","classExists","contains","count","countBetween","digits","directory","duplicate","email","endsWith","enumCaseExists","enumValueExists","eq","false","file","fileExists","float","forEach","forKeys","fulfills","greaterThan","greaterThanEq","hasIndices","implementsInterface","inArray","instancedPropertyExists","integer","integerish","interfaceExists","ip","ipv4","ipv6","isAOf","isAnyOf","isArray","isArrayAccessible","isCallable","isCountable","isEmpty","isInstanceOf","isInstanceOfAny","isIterable","isList","isMap","isNonEmptyList","isNonEmptyMap","isNotA","keyExists","keyNotExists","keysExists","length","lengthBetween","lessThan","lessThanEq","lower","maxCount","maxLength","methodExists","methodNotExists","minCount","minLength","natural","notContains","notEmpty","notEndsWith","notEq","notFalse","notInstanceOf","notNull","notRegex","notSame","notStartsWith","notWhitespaceOnly","null","nullOr","nullOrAlnum","nullOrAlpha","nullOrArrayContains","nullOrBoolean","nullOrClassExists","nullOrContains","nullOrCount","nullOrCountBetween","nullOrDigits","nullOrDirectory","nullOrEmail","nullOrEndsWith","nullOrEnumCaseExists","nullOrEnumValueExists","nullOrEq","nullOrFalse","nullOrFile","nullOrFileExists","nullOrFloat","nullOrFulfills","nullOrGreaterThan","nullOrGreaterThanEq","nullOrHasIndices","nullOrImplementsInterface","nullOrInArray","nullOrInstancedPropertyExists","nullOrInteger","nullOrIntegerish","nullOrInterfaceExists","nullOrIp","nullOrIpv4","nullOrIpv6","nullOrIsAOf","nullOrIsAnyOf","nullOrIsArray","nullOrIsArrayAccessible","nullOrIsCallable","nullOrIsCountable","nullOrIsEmpty","nullOrIsInstanceOf","nullOrIsInstanceOfAny","nullOrIsIterable","nullOrIsList","nullOrIsMap","nullOrIsNonEmptyList","nullOrIsNonEmptyMap","nullOrIsNotA","nullOrKeyExists","nullOrKeyNotExists","nullOrKeysExists","nullOrLength","nullOrLengthBetween","nullOrLessThan","nullOrLessThanEq","nullOrLower","nullOrMaxCount","nullOrMaxLength","nullOrMethodExists","nullOrMethodNotExists","nullOrMinCount","nullOrMinLength","nullOrNatural","nullOrNotContains","nullOrNotEmpty","nullOrNotEndsWith","nullOrNotEq","nullOrNotFalse","nullOrNotInstanceOf","nullOrNotNull","nullOrNotRegex","nullOrNotSame","nullOrNotStartsWith","nullOrNotWhitespaceOnly","nullOrNumeric","nullOrObject","nullOrOneOf","nullOrPositiveInteger","nullOrPrivatePropertyExists","nullOrPropertyExists","nullOrPropertyNotExists","nullOrProtectedPropertyExists","nullOrPublicPropertyExists","nullOrRange","nullOrReadable","nullOrRegex","nullOrResource","nullOrSame","nullOrScalar","nullOrStartsWith","nullOrStartsWithLetter","nullOrStaticPropertyExists","nullOrString","nullOrStringNotEmpty","nullOrSubclassOf","nullOrThrows","nullOrTrue","nullOrType","nullOrUnicodeLetters","nullOrUniqueValues","nullOrUpper","nullOrUuid","nullOrValidArrayKey","nullOrWritable","numeric","object","oneOf","or","positiveInteger","privatePropertyExists","propertyExists","propertyNotExists","protectedPropertyExists","publicPropertyExists","range","readable","regex","resource","same","scalar","startsWith","startsWithLetter","staticPropertyExists","string","stringNotEmpty","subclassOf","throws","true","type","unicodeLetters","uniqueValues","upper","uuid","validArrayKey","when","whenAt","writable"];

    protected function assertMethodIsCovered(string $name): bool
    {
        return in_array($name, $this->coveredMethods, true);
    }

    protected function ensureAssertMethodIsCovered(string $name): void
    {
        $class = static::class;

        if (!$this->assertMethodIsCovered($name)) {
            throw new BadMethodCallException("Call to undefined method $class::$name()");
        }
    }
}
